version: '3'
services: #services are the containers
  flask_app_1: #name of the container
    build: ./flask1 #image being built
    ports: #7001 is the port of the host machine and #5002 is the port of the container
      - "7001:5002"
    volumes: #directory of the file
      - ./flask1:/app
  flask_app_2: #name of the container
    build: ./flask2 #image being built
    ports: #7002 is the port of the host machine and #5001 is the port of the container
      - "7002:5001"
    volumes: #directory of the file
      - ./flask2:/app

