version: '3'
services:
  flask_app_1:
    build: ./flask1
    ports:
      - "7001:5002"
    volumes:
      - ./flask1:/app
  flask_app_2:
    build: ./flask2
    ports:
      - "7002:5001"
    volumes:
      - ./flask2:/app

